version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hansen
      POSTGRES_PASSWORD: junctionhahaa
    ports:
      - "5432:5432" 
  backend:
    build: .
    command: bash -c "cargo run"
    ports:
      - "8000:8000"